import type { MappedCodegenPayload, MappedDendraPayload, MappedINaturalistPayload } from './mappers';

function asPythonStringArray(values: string[]): string {
  return `[${values.map((value) => `'${value.replace(/'/g, "\\'")}'`).join(', ')}]`;
}

function asPythonNullableString(value?: string): string {
  return value ? `'${value.replace(/'/g, "\\'")}'` : 'None';
}

function asPythonNullableNumber(value?: number): string {
  return typeof value === 'number' ? String(value) : 'None';
}

function renderINaturalistParams(payload: MappedINaturalistPayload): string[] {
  return [
    "    # Dangermond Preserve expanded search bounds",
    "    'swlat': 34.35,",
    "    'swlng': -120.55,",
    "    'nelat': 34.62,",
    "    'nelng': -120.30,",
    `    'taxon_name': ${asPythonStringArray(payload.filters.selectedTaxa)},`,
    `    'species_guess': ${asPythonStringArray(payload.filters.selectedSpecies)},`,
    `    'd1': ${asPythonNullableString(payload.filters.startDate)},`,
    `    'd2': ${asPythonNullableString(payload.filters.endDate)},`,
    `    'per_page': 200,`,
    `    'quality_grade': ${payload.filters.excludeAllSpecies ? "'any'" : "'research'"},`,
    '    # Remove empty params before request',
  ];
}

function renderDendraParams(payload: MappedDendraPayload): string[] {
  return [
    `    'station_id': ${asPythonNullableNumber(payload.filters.selectedStationId)},`,
    `    'datastream_id': ${asPythonNullableNumber(payload.filters.selectedDatastreamId)},`,
    `    'start': ${asPythonNullableString(payload.filters.startDate)},`,
    `    'end': ${asPythonNullableString(payload.filters.endDate)},`,
    `    'aggregation': ${asPythonNullableString(payload.filters.aggregation)},`,
    `    'active_only': ${payload.filters.showActiveOnly ? 'True' : 'False'},`,
    '    # Remove empty params before request',
  ];
}

export function renderPythonSnippet(payload: MappedCodegenPayload): string {
  const paramsLines = payload.dataSource === 'inaturalist'
    ? renderINaturalistParams(payload)
    : renderDendraParams(payload);
  const endpoint = payload.dataSource === 'inaturalist'
    ? 'https://api.inaturalist.org/v1/observations'
    : 'https://dendra.science/api/v5/query';

  return [
    '# Generated by V2 Export Builder',
    `# Layer: ${payload.layerName} (${payload.layerId})`,
    `# View: ${payload.viewName} (${payload.viewId})`,
    payload.filterSummary ? `# Filters: ${payload.filterSummary}` : '# Filters: none',
    typeof payload.filteredResultCount === 'number'
      ? `# Estimated matching results: ${payload.filteredResultCount}`
      : '# Estimated matching results: unknown',
    '',
    'import requests',
    'import pandas as pd',
    '',
    `endpoint = '${endpoint}'`,
    'params = {',
    ...paramsLines,
    '}',
    '',
    'clean_params = {k: v for k, v in params.items() if v not in (None, "", [], {})}',
    'response = requests.get(endpoint, params=clean_params, timeout=60)',
    'response.raise_for_status()',
    'payload = response.json()',
    '',
    payload.dataSource === 'inaturalist'
      ? "rows = payload.get('results', [])"
      : "rows = payload.get('data', payload)",
    "df = pd.json_normalize(rows) if isinstance(rows, list) else pd.DataFrame([rows])",
    "print(f'Loaded {len(df)} rows')",
    'df.head()',
  ].join('\n');
}

