import type { MappedCodegenPayload, MappedDendraPayload, MappedINaturalistPayload } from './mappers';

function asRStringArray(values: string[]): string {
  if (values.length === 0) {
    return 'character(0)';
  }
  return `c(${values.map((value) => `"${value.replace(/"/g, '\\"')}"`).join(', ')})`;
}

function asRNullableString(value?: string): string {
  return value ? `"${value.replace(/"/g, '\\"')}"` : 'NULL';
}

function asRNullableNumber(value?: number): string {
  return typeof value === 'number' ? String(value) : 'NULL';
}

function renderINaturalistParams(payload: MappedINaturalistPayload): string[] {
  return [
    `  taxon_name = ${asRStringArray(payload.filters.selectedTaxa)},`,
    `  species_guess = ${asRStringArray(payload.filters.selectedSpecies)},`,
    `  d1 = ${asRNullableString(payload.filters.startDate)},`,
    `  d2 = ${asRNullableString(payload.filters.endDate)},`,
    '  per_page = 200,',
    `  quality_grade = ${payload.filters.excludeAllSpecies ? '"any"' : '"research"'}`,
  ];
}

function renderDendraParams(payload: MappedDendraPayload): string[] {
  return [
    `  station_id = ${asRNullableNumber(payload.filters.selectedStationId)},`,
    `  datastream_id = ${asRNullableNumber(payload.filters.selectedDatastreamId)},`,
    `  start = ${asRNullableString(payload.filters.startDate)},`,
    `  end = ${asRNullableString(payload.filters.endDate)},`,
    `  aggregation = ${asRNullableString(payload.filters.aggregation)},`,
    `  active_only = ${payload.filters.showActiveOnly ? 'TRUE' : 'FALSE'}`,
  ];
}

export function renderRSnippet(payload: MappedCodegenPayload): string {
  const paramsLines = payload.dataSource === 'inaturalist'
    ? renderINaturalistParams(payload)
    : renderDendraParams(payload);
  const endpoint = payload.dataSource === 'inaturalist'
    ? 'https://api.inaturalist.org/v1/observations'
    : 'https://dendra.science/api/v5/query';

  return [
    '# Generated by V2 Export Builder',
    `# Layer: ${payload.layerName} (${payload.layerId})`,
    `# View: ${payload.viewName} (${payload.viewId})`,
    payload.filterSummary ? `# Filters: ${payload.filterSummary}` : '# Filters: none',
    typeof payload.filteredResultCount === 'number'
      ? `# Estimated matching results: ${payload.filteredResultCount}`
      : '# Estimated matching results: unknown',
    '',
    'library(httr2)',
    'library(jsonlite)',
    'library(dplyr)',
    '',
    '`%||%` <- function(x, y) if (is.null(x) || length(x) == 0) y else x',
    '',
    `endpoint <- "${endpoint}"`,
    'params <- list(',
    ...paramsLines,
    ')',
    '',
    'params <- params[!vapply(params, function(x) is.null(x) || length(x) == 0, logical(1))]',
    'response <- request(endpoint) |> req_url_query(!!!params) |> req_perform()',
    'payload <- resp_body_json(response, simplifyVector = FALSE)',
    '',
    payload.dataSource === 'inaturalist'
      ? "rows <- payload$results %||% list()"
      : "rows <- payload$data %||% payload",
    'df <- jsonlite::flatten(bind_rows(rows))',
    "cat(sprintf('Loaded %d rows\\n', nrow(df)))",
    'head(df)',
  ].join('\n');
}

